FRAME_DURATION_MS = 32
WINDOW_UPDATE_INTERVAL_FRAMES = 60
DELTA_TIME = FRAME_DURATION_MS / 1000

GRAVITY_ACCELERATION = 1098

RAGDOLL_ACCELERATION = 100
RAGDOLL_DAMPING = 0.85
RAGDOLL_STIFFNES = 0.85
RAGDOLL_BOUNCE_FACTOR = 0.7

STICKMAN_WIDTH = 100
STICKMAN_HEIGHT = 145

STICKMAN_DEFAULT_DECIDE_COOLDOWN = 3

STROKE = 9
RAGPOINT_RADIUS = 10
HOLLOW_HEAD_DIAMETER = 38
FILLED_HEAD_DIAMETER = 30

TORSO_LENGTH = 37

HIP_HEIGHT_FROM_TOP = STROKE + HOLLOW_HEAD_DIAMETER + TORSO_LENGTH

UPPER_ARM_LENGTH = 24
FOREARM_LENGTH = 23

UPPER_LEG_LENGTH = 28
LOWER_LEG_LENGTH = 27

DEFAULT_ANIMATION_CYCLE_DURATION = 0.5
DISTANCE_PER_WALK_CYCLE = 67

DEFAULT_WALK_SPEED = 170

SCORE_MARGIN = 0.3